### PR TITLE
Added working test-helper functions and Tests

### PR DESCRIPTION
**Pull request by frunjik**
This adds new (working) test-helper functions and uses the test-helpers in newly written tests
- Added new working test-helper functions
- Added tests
- updated to ember-cli@2.5.0
- updated to ember@2.5.0
- updated to ember-data@2.5.0
- updated to ember-mirage@0.2.1

### CODE REVIEW

**Comment by jackmatt2** [comment]
Awesome 👍 , will release later this week.

**Comment by frunjik** [comment]
Additional note:
Beware that the baseurl has changed from: '/ember-aupac-typeahead' to '/' ...

**Comment by frunjik** [comment]
Is there something preventing you from making a release with this in ?
Let me know if I can do something to help...

**Comment by jackmatt2** [comment]
Sorry, I will do a release this weekend.

**Comment by jackmatt2** [comment]
@frunjik I have released this now at 2.0.8.  I had to comment out a couple of tests in  `typeahead-test.js` after updating to ember 2.8.0.  Are you able to take a look as to why?

**Comment by frunjik** [comment]
made a PR:

https://github.com/aupac/ember-aupac-typeahead/pull/27/files

2016-10-04 14:21 GMT+02:00 Jack Matthews notifications@github.com:

**Pull request merged**
